# Cleanig the Datasets

products dataset

In [51]:
import pandas as pd
products=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\Products_raw.xlsx')

In [52]:
products

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1213,SKU00859,Snackify Floor Cleaner 100g,Home Care,Floor Cleaner,Snackify,18,94.47,166.26
1214,SKU01137,DailyDairy Meat 500g,Frozen,Meat,DailyDairy,18,106.15,149.18
1215,SKU00895,AquaFizz Powder Combo,Baby Care,Powder,AquaFizz,5,44.13,77.21
1216,SKU00364,FrostBite Cheese 1kg,Dairy,Cheese,FrostBite,5,64.02,101.28
1217,SKU00229,Nestora Ice Cream Pack,Frozen,Ice Cream,Nestora,18,142.26,220.64

In [53]:
products.dtypes

SKU_ID           object
SKU_Name         object
Category         object
Sub_Category     object
Brand            object
Tax_Percent       int64
Unit_Cost       float64
MRP             float64
dtype: object

In [54]:
products.describe()

       Tax_Percent    Unit_Cost          MRP
count  1218.000000  1206.000000  1218.000000
mean     11.472906    88.618284   135.305525
std       5.656826    56.429851    88.976958
min       5.000000    10.760000    16.390000
25%       5.000000    47.922500    73.557500
50%      12.000000    76.105000   114.445000
75%      18.000000   116.030000   173.465000
max      18.000000   516.910000   807.170000

In [55]:
products.isnull().sum()

SKU_ID           0
SKU_Name         0
Category         0
Sub_Category     0
Brand           12
Tax_Percent      0
Unit_Cost       12
MRP              0
dtype: int64

In [56]:
products.SKU_ID.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1213     True
1214     True
1215     True
1216     True
1217     True
Name: SKU_ID, Length: 1218, dtype: bool

In [57]:
products=products.drop_duplicates(subset=['SKU_ID'])

In [58]:
products

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1197,SKU01198,AquaFizz Namkeen 250g,Snacks,Namkeen,AquaFizz,12,17.37,25.21
1198,SKU01199,FreshCo Deodorant 1L,Personal Care,Deodorant,FreshCo,18,62.35,82.94
1199,SKU01200,Snackify Toothpaste 500g,Personal Care,Toothpaste,Snackify,18,57.02,98.97
1206,SKU00484,HealthHub Skin Care 500g,Personal Care,Skin Care,HealthHub,18,21.13,36.40
1208,SKU00599,FreshCo Skin Care 2L,Personal Care,Skin Care,FreshCo,18,79.40,139.94

Filling the null values in Brand columns

In [59]:
mask = products['Brand'].isna()

products.loc[mask, 'Brand'] = (
    products.loc[mask].apply(
        lambda x: x['SKU_Name'].split(x['Sub_Category'])[0].strip()
        if pd.notna(x['Sub_Category']) and x['Sub_Category'] in x['SKU_Name']
        else x['SKU_Name'].split()[0],
        axis=1
    )
)

In [60]:
products.loc[:,'SKU_ID'] = products['SKU_ID'].str.replace('-', '', regex=False)

In [61]:
products.SKU_ID.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1197    False
1198    False
1199    False
1206    False
1208    False
Name: SKU_ID, Length: 1202, dtype: bool

In [63]:
# Find the SKU_IDs in inventory that are missing from the products table
missing_inv_skus = inventory[~inventory['SKU_ID'].isin(products['SKU_ID'])]['SKU_ID'].unique()

# Create a temporary DataFrame for them
missing_inv_df = pd.DataFrame({'SKU_ID': missing_inv_skus})

# Append them to your master product DataFrame
product = pd.concat([products, missing_inv_df], ignore_index=True)

print(f"Added {len(missing_inv_skus)} missing SKUs from Inventory.")

Added 741 missing SKUs from Inventory.

In [64]:
products.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\products_cleaned.xlsx",index = False)

Customers dataset

In [1]:
import pandas as pd
customers=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\customers_raw.xlsx')

In [2]:
customers

      Customer_ID       City          Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22 00:00:00           New
1      CUST000002     Mumbai  2025-04-19 00:00:00           New
2      CUST000003  Ahmedabad  2025-03-31 00:00:00     Returning
3      CUST000004      Delhi  2025-01-21 00:00:00     Returning
4      CUST000005  Hyderabad  2025-01-26 00:00:00     Returning
...           ...        ...                  ...           ...
15295  CUST013214      Delhi  2025-01-17 00:00:00           New
15296  CUST000609  Hyderabad  2025-05-25 00:00:00           New
15297  CUST004885  Ahmedabad  2025-05-19 00:00:00           New
15298  CUST013475     Jaipur  2025-01-07 00:00:00           New
15299  CUST004331  Bengaluru  2025-05-22 00:00:00           New

[15300 rows x 4 columns]

In [3]:
customers.describe()

       Customer_ID       City Signup_Date Customer_Type
count        15300      15147       15300         15300
unique       15016         10         203             3
top     CUST009412  Bengaluru  32/13/2025           New
freq             2       2147         153          9117

In [4]:
customers.isnull().sum()

Customer_ID        0
City             153
Signup_Date        0
Customer_Type      0
dtype: int64

In [5]:
customers.Customer_ID.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
15295     True
15296     True
15297     True
15298    False
15299     True
Name: Customer_ID, Length: 15300, dtype: bool

In [6]:
customers = customers.drop_duplicates(subset=['Customer_ID']).copy()

customers['City'] = customers['City'].fillna('Not Mentioned')

In [7]:
customers.dtypes

Customer_ID      object
City             object
Signup_Date      object
Customer_Type    object
dtype: object

In [8]:
customers['Signup_Date'] = pd.to_datetime(
    customers['Signup_Date'], 
    dayfirst=True, 
    errors='coerce'
)

In [9]:
customers.dtypes

Customer_ID              object
City                     object
Signup_Date      datetime64[ns]
Customer_Type            object
dtype: object

In [10]:
# Extract only digits
customers['Customer_ID'] = customers['Customer_ID'].str.extract(r'(\d+)')

# Convert to integer then format with leading zeros
customers['Customer_ID'] = customers['Customer_ID'].astype(int)

customers['Customer_ID'] = customers['Customer_ID'].apply(
    lambda x: f'CUST{x:06d}'
)

In [11]:
customers

      Customer_ID       City Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22           New
1      CUST000002     Mumbai  2025-04-19           New
2      CUST000003  Ahmedabad  2025-03-31     Returning
3      CUST000004      Delhi  2025-01-21     Returning
4      CUST000005  Hyderabad  2025-01-26     Returning
...           ...        ...         ...           ...
15253  CUST011637      Kochi  2025-01-14     Returning
15257  CUST877828    Chennai  2025-02-24           New
15278  CUST482562    Chennai  2025-04-28           New
15286  CUST066492  Bengaluru  2025-03-01           New
15298  CUST013475     Jaipur  2025-01-07           New

[15016 rows x 4 columns]

In [32]:
# Assuming 'sales' as  transaction dataframe
# Calculate the snapshot date (day after the last purchase in the dataset)
snapshot_date = sales['Order_Date'].max() + pd.Timedelta(days=1)

# Aggregate data by Customer_ID
rfm = sales.groupby('Customer_ID').agg({
    'Order_Date': lambda x: (snapshot_date - x.max()).days,
    'Order_ID': 'nunique',
    'Selling_Price': 'sum'
})

# Rename columns for clarity
rfm.rename(columns={
    'Order_Date': 'Recency',
    'Order_ID': 'Frequency',
    'Selling_Price': 'Monetary'
}, inplace=True)

In [33]:
rfm

             Recency  Frequency  Monetary
Customer_ID
CUST000001     204.0          3    386.04
CUST000002     160.0          9    664.85
CUST000003     210.0          5    396.30
CUST000004     205.0          3    374.48
CUST000005     193.0          2     94.17
...              ...        ...       ...
CUST014995     215.0          6    665.37
CUST014996     238.0          4    494.95
CUST014997     183.0          3    171.20
CUST014999     204.0          5    408.95
CUST015000     298.0          2    201.77

[14907 rows x 3 columns]

In [92]:
customers.Customer_ID.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
15253    False
15257    False
15278    False
15286    False
15298    False
Name: Customer_ID, Length: 15016, dtype: bool

In [35]:
# Find the Customer_IDs in sales that are missing from the customers table
missing_customers = sales[~sales['Customer_ID'].isin(customers['Customer_ID'])]['Customer_ID'].unique()

# Create a temporary DataFrame for these 200 missing customers
missing_cust_df = pd.DataFrame({'Customer_ID': missing_customers})

# Append (concat) them to your master customer DataFrame
customers = pd.concat([customers, missing_cust_df], ignore_index=True)

print(f"Added {len(missing_customers)} missing customers.")

Added 225 missing customers.

In [37]:
customers.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\customers_cleaned.xlsx",index = False)

Cleaning the Vendors supply Dataset

In [94]:
import pandas as pd
vendors=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\vendors_raw.xlsx')

In [95]:
vendors

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18 00:00:00,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM1,2025-03-16 00:00:00,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15 00:00:00,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03 00:00:00,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24 00:00:00,2025-03-27 00:00:00,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21 00:00:00,2025-05-27 00:00:00,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,che01,2025-05-10 00:00:00,2025-05-18 00:00:00,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22 00:00:00,2025-01-25 00:00:00,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02 00:00:00,2025-06-08 00:00:00,2025-06-08 00:00:00,65,50.51

In [96]:
vendors.dtypes

PO_ID                      object
Vendor_ID                  object
SKU_ID                     object
Store_ID                   object
PO_Date                    object
Expected_Delivery_Date     object
Actual_Delivery_Date       object
Supplied_Quantity           int64
Procurement_Cost          float64
dtype: object

In [97]:
vendors.describe()

       Supplied_Quantity  Procurement_Cost
count       30450.000000      30298.000000
mean           59.965583         91.023856
std             7.090200         58.010590
min            36.000000         10.250000
25%            55.000000         49.250000
50%            60.000000         77.610000
75%            65.000000        118.870000
max            91.000000        567.830000

In [98]:
vendors.isnull().sum()

PO_ID                       0
Vendor_ID                   0
SKU_ID                      0
Store_ID                    0
PO_Date                     0
Expected_Delivery_Date      0
Actual_Delivery_Date        0
Supplied_Quantity           0
Procurement_Cost          152
dtype: int64

In [99]:
vendors.PO_ID.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
30445     True
30446     True
30447     True
30448     True
30449     True
Name: PO_ID, Length: 30450, dtype: bool

In [100]:
vendors=vendors.drop_duplicates(subset=['PO_ID'])

In [101]:
vendors

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18 00:00:00,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM1,2025-03-16 00:00:00,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15 00:00:00,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03 00:00:00,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
29995,PO329995,VEND0058,SKU00178,HYD-02,2025-03-24 00:00:00,2025-03-28 00:00:00,2025-03-28 00:00:00,54,51.90
29996,PO329996,VEND0058,SKU00087,MUM-02,2025-02-15 00:00:00,2025-02-17 00:00:00,2025-02-17 00:00:00,62,133.57
29997,PO329997,VEND0018,SKU00152,JAI-01,2025-06-16 00:00:00,2025-06-23 00:00:00,2025-06-23 00:00:00,77,121.77
29998,PO329998,VEND0017,SKU00201,CHE-05,2025-03-08 00:00:00,2025-03-16 00:00:00,2025-03-16 00:00:00,60,121.98
29999,PO329999,VEND0056,SKU00503,KOC-05,2025-03-29 00:00:00,2025-04-05 00:00:00,2025-04-08 00:00:00,58,47.11

In [102]:

vendors.loc[:, 'Store_ID'] = (
    vendors['Store_ID']
    .astype(str)
    .str.upper()
    .str.replace(r'^([A-Z]{3})-?(\d+)$', r'\1-\2', regex=True)
)

In [103]:
vendors = vendors.copy()

date_cols = ['PO_Date', 'Expected_Delivery_Date', 'Actual_Delivery_Date']

for col in date_cols:
    vendors.loc[:, col] = pd.to_datetime(vendors[col], errors='coerce')

In [104]:
# Check formats
po_valid = vendors['PO_ID'].str.match(r'^PO\d{6}$')
vendor_valid = vendors['Vendor_ID'].str.match(r'^VEND\d{4}$')
sku_valid = vendors['SKU_ID'].str.match(r'^SKU\d{5}$')

# Check if all values are valid
print("PO_ID valid:", po_valid.all())
print("Vendor_ID valid:", vendor_valid.all())
print("SKU_ID valid:", sku_valid.all())

PO_ID valid: True
Vendor_ID valid: True
SKU_ID valid: False

In [105]:
# Remove the hyphen from SKU_ID
vendors['SKU_ID'] = vendors['SKU_ID'].str.replace('-', '', regex=False)

# Now re-run your validation check
pattern = r'^SKU\d{5}$'
sku_valid = vendors['SKU_ID'].astype(str).str.match(pattern)

print("SKU_ID valid now:", sku_valid.all())

SKU_ID valid now: True

In [106]:
# 1. Strip whitespace and make everything uppercase
vendors['Store_ID'] = vendors['Store_ID'].astype(str).str.strip().str.upper()

# 2. Remove any existing hyphens so we can re-insert them correctly
vendors['Store_ID'] = vendors['Store_ID'].str.replace('-', '', regex=False)
# 3. Fix single digits: If it's 3 letters + 1 digit (e.g., HYD1 -> HYD01)
vendors['Store_ID'] = vendors['Store_ID'].str.replace(
    r'^([A-Z]{3})(\d{1})$', 
    r'\g<1>0\g<2>',  # Use \g<1> to keep group 1 separate from the zero
    regex=True
)

# 4. Insert the hyphen: Turn 3 letters + 2 digits into AAA-00 (e.g., HYD01 -> HYD-01)
vendors['Store_ID'] = vendors['Store_ID'].str.replace(
    r'^([A-Z]{3})(\d{2})$', 
    r'\g<1>-\g<2>', 
    regex=True
)

In [107]:
vendors.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\vendors_cleaned.xlsx",index = False)

Inventory daily Dataset

In [38]:
inventory=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\inventory_raw.xlsx')

In [39]:
inventory

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01 00:00:00,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25 00:00:00,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07 00:00:00,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24 00:00:00,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05 00:00:00,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27 00:00:00,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08 00:00:00,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12 00:00:00,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07 00:00:00,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13 00:00:00,BEN-04,SKU00201,31,101,99.0,425.0

In [40]:
inventory['Date'] = pd.to_datetime(
    inventory['Date'],
    dayfirst=True,
    errors='coerce'
)

In [41]:
inventory.dtypes

Date               datetime64[ns]
Store_ID                   object
SKU_ID                     object
Reorder_Level               int64
Opening_Stock               int64
Closing_Stock             float64
Warehouse_Stock           float64
dtype: object

In [42]:
inventory.isnull().sum()

Date               505
Store_ID             0
SKU_ID               0
Reorder_Level        0
Opening_Stock        0
Closing_Stock      252
Warehouse_Stock    252
dtype: int64

In [43]:
# Standardize Store_ID format -> CITY-01
inventory['Store_ID'] = (
    inventory['Store_ID']
    .astype(str)
    .str.strip()
    .str.upper()
)

# Standardize SKU_ID format -> SKU00001
inventory['SKU_ID'] = (
    inventory['SKU_ID']
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace('-', '', regex=False)
)

# Ensure SKU_ID has correct zero padding
inventory['SKU_ID'] = inventory['SKU_ID'].str.extract(r'(\d+)')[0].astype(int)
inventory['SKU_ID'] = inventory['SKU_ID'].apply(lambda x: f'SKU{x:05d}')

In [44]:
inventory

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13,BEN-04,SKU00201,31,101,99.0,425.0

In [45]:
# 1. Count the number of duplicate entries based on the three columns
duplicate_count = inventory.duplicated(subset=['Date', 'Store_ID', 'SKU_ID']).sum()

print(f"Number of duplicate rows: {duplicate_count}")
if duplicate_count > 0:
    duplicates = inventory[inventory.duplicated(subset=['Date', 'Store_ID', 'SKU_ID'], keep=False)]
    print(duplicates.sort_values(by=['Date', 'Store_ID']))

Number of duplicate rows: 517
            Date Store_ID    SKU_ID  Reorder_Level  Opening_Stock  \
34775 2025-01-01   AHM-03  SKU00142             27              4
50420 2025-01-01   AHM-03  SKU00142             27              4
49269 2025-01-01   CHE-03  SKU00733             25             14
50105 2025-01-01   CHE-03  SKU00733             25             14
24725 2025-01-01   CHE-04  SKU00409             18             97
...          ...      ...       ...            ...            ...
36801 2025-06-30   JAI-02  SKU00624             10             44
36095 2025-06-30   KOC-03  SKU00284             24             58
50086 2025-06-30   KOC-03  SKU00284             24             58
11922        NaT   KOC-05  SKU00380             18             13
21011        NaT   KOC-05  SKU00380             37             61

       Closing_Stock  Warehouse_Stock
34775            0.0            460.0
50420            0.0            460.0
49269           11.0            357.0
50105           11.0            357.0
24725           99.0            176.0
...              ...              ...
36801           37.0            437.0
36095           52.0            345.0
50086           52.0            345.0
11922           12.0            488.0
21011           56.0             58.0

[1030 rows x 7 columns]

In [46]:
# Remove duplicates based on the specific column combination
inventory = inventory.drop_duplicates(subset=['Date', 'Store_ID', 'SKU_ID'], keep='first')

# Reset the index since rows were removed
inventory = inventory.reset_index(drop=True)

In [47]:
inventory

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
49978,2025-05-09,AHM03,SKU00851,15,29,NaN,252.0
49979,2025-02-23,AHM-04,SKU00205,18,67,66.0,441.0
49980,2025-03-07,KOC-04,SKU00931,18,97,92.0,490.0
49981,2025-05-02,KOL-05,SKU00031,15,64,NaN,106.0
49982,2025-05-07,CHE-03,SKU01064,36,9,4.0,421.0

In [65]:
# Find the SKU_IDs in inventory that are missing from the products table
missing_inv_skus = inventory[~inventory['SKU_ID'].isin(products['SKU_ID'])]['SKU_ID'].unique()

# Create a temporary DataFrame for them
missing_inv_df = pd.DataFrame({'SKU_ID': missing_inv_skus})

# Append them to your master product DataFrame
products = pd.concat([products, missing_inv_df], ignore_index=True)

print(f"Added {len(missing_inv_skus)} missing SKUs from Inventory.")

Added 741 missing SKUs from Inventory.

In [66]:
inventory.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\inventory_cleaned.xlsx",index = False)

Promotions Dataset

In [22]:
promotions=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\promotions.xlsx')

In [23]:
promotions

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28 00:00:00,2025-06-07 00:00:00,Beverages,196431.0
1,PR0002,Flat %,2025-06-13 00:00:00,2025-06-28 00:00:00,Home Care,123013.0
2,PR0003,Flat %,2025-06-10 00:00:00,2025-07-07 00:00:00,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06 00:00:00,2025-04-25 00:00:00,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10 00:00:00,2025-04-01 00:00:00,Frozen,63424.0
...,...,...,...,...,...,...
205,PR0021,Member Exclusive,2025-03-12 00:00:00,2025-03-20 00:00:00,Frozen,236449.0
206,PR0200,Member Exclusive,2025-01-27 00:00:00,2025-02-15 00:00:00,Beverages,90374.0
207,PR0009,Member Exclusive,2025-04-30 00:00:00,2025-05-11 00:00:00,Baby Care,778423.0
208,PR0040,BOGO,2025-06-10 00:00:00,2025-06-30 00:00:00,Personal Care,782218.0
209,PR0089,Flat %,2025-02-06 00:00:00,2025-03-03 00:00:00,Baby Care,396667.0

In [24]:
date_cols = ['Start_Date', 'End_Date']

promotions[date_cols] = promotions[date_cols].apply(
    lambda x: pd.to_datetime(x, errors='coerce').dt.date
)

In [25]:
promotions.isnull().sum()

Promo_ID           0
Promo_Type         0
Start_Date         2
End_Date           2
Target_Category    0
Promo_Budget       4
dtype: int64

In [26]:
promotions.Promo_ID.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
205     True
206     True
207     True
208     True
209     True
Name: Promo_ID, Length: 210, dtype: bool

In [27]:
promotions = promotions.drop_duplicates(subset=['Promo_ID'])

In [165]:
promotions.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\promotions_cleaned.xlsx",index = False)

Sales Dataset

In [14]:
sales=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\sales_raw.xlsx')
sales

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01 00:00:00,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PROMO-9999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14 00:00:00,HYD-03,CUST004865,SKU01082,6,273.62,173.52,NaN,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05 00:00:00,BEN-05,CUST006245,SKU00901,2,58.95,4.42,NaN,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23 00:00:00,JAI-02,CUST009196,SKU00524,2,188.08,23.20,NaN,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01 00:00:00,PUN-01,CUST000981,SKU00215,2,91.13,16.68,NaN,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08 00:00:00,MUM-01,CUST000930,SKU00727,3,41.21,10.77,NaN,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21 00:00:00,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PR0020,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01 00:00:00,PUN-03,CUST009816,SKU00798,6,220.12,222.18,NaN,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10 00:00:00,HYD-02,CUST014782,SKU00777,3,76.19,35.70,NaN,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09 00:00:00,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PR0011,Home Delivery,Card,Delivered

In [17]:
sales.Order_ID.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
81595     True
81596     True
81597     True
81598     True
81599     True
Name: Order_ID, Length: 81600, dtype: bool

In [18]:
sales = sales.drop_duplicates(subset='Order_ID')

In [19]:
sales.isnull().sum()

Order_ID               0
Order_Date             0
Store_ID               0
Customer_ID            0
SKU_ID                 0
Quantity               0
Selling_Price        317
Discount_Amount      318
Promo_ID           50468
Delivery_Type          0
Payment_Mode         324
Order_Status           0
dtype: int64

In [20]:
# Create a filtered dataframe for analysis
sales = sales[sales['Order_Status'] != 'Cancelled'].copy()

In [28]:
# Get valid promo ids from promotions table
valid_promo_ids = promotions['Promo_ID'].dropna().unique()

# Replace invalid Promo_IDs in sales with NaN
sales.loc[
    ~sales['Promo_ID'].isin(valid_promo_ids),
    'Promo_ID'
] = pd.NA

# View result
sales['Promo_ID'].unique()

array([<NA>, 'PR0065', 'PR0127', 'PR0131', 'PR0182', 'PR0186', 'PR0122',
       'PR0156', 'PR0155', 'PR0111', 'PR0185', 'PR0021', 'PR0197',
       'PR0121', 'PR0015', 'PR0168', 'PR0037', 'PR0091', 'PR0093',
       'PR0033', 'PR0005', 'PR0132', 'PR0094', 'PR0084', 'PR0160',
       'PR0178', 'PR0085', 'PR0146', 'PR0096', 'PR0175', 'PR0098',
       'PR0097', 'PR0013', 'PR0198', 'PR0019', 'PR0004', 'PR0145',
       'PR0056', 'PR0128', 'PR0066', 'PR0170', 'PR0162', 'PR0176',
       'PR0143', 'PR0048', 'PR0011', 'PR0087', 'PR0038', 'PR0101',
       'PR0124', 'PR0189', 'PR0041', 'PR0054', 'PR0194', 'PR0126',
       'PR0138', 'PR0105', 'PR0049', 'PR0141', 'PR0119', 'PR0058',
       'PR0046', 'PR0039', 'PR0017', 'PR0102', 'PR0177', 'PR0018',
       'PR0090', 'PR0159', 'PR0184', 'PR0089', 'PR0171', 'PR0062',
       'PR0181', 'PR0079', 'PR0148', 'PR0153', 'PR0150', 'PR0112',
       'PR0006', 'PR0173', 'PR0034', 'PR0045', 'PR0125', 'PR0104',
       'PR0036', 'PR0088', 'PR0083', 'PR0117', 'PR0023', 'PR0161',
       'PR0009', 'PR0051', 'PR0123', 'PR0140', 'PR0188', 'PR0134',
       'PR0099', 'PR0061', 'PR0187', 'PR0035', 'PR0129', 'PR0092',
       'PR0060', 'PR0095', 'PR0008', 'PR0069', 'PR0130', 'PR0070',
       'PR0154', 'PR0118', 'PR0029', 'PR0002', 'PR0106', 'PR0116',
       'PR0076', 'PR0190', 'PR0040', 'PR0158', 'PR0078', 'PR0139',
       'PR0063', 'PR0192', 'PR0044', 'PR0026', 'PR0200', 'PR0191',
       'PR0057', 'PR0053', 'PR0077', 'PR0067', 'PR0169', 'PR0180',
       'PR0086', 'PR0137', 'PR0110', 'PR0014', 'PR0100', 'PR0059',
       'PR0024', 'PR0052', 'PR0055', 'PR0047', 'PR0196', 'PR0028',
       'PR0030', 'PR0064', 'PR0109', 'PR0149', 'PR0107', 'PR0073',
       'PR0032', 'PR0071', 'PR0103', 'PR0043', 'PR0108', 'PR0115',
       'PR0068', 'PR0050', 'PR0164', 'PR0012', 'PR0027', 'PR0007',
       'PR0172', 'PR0081', 'PR0166', 'PR0010', 'PR0025', 'PR0075',
       'PR0120', 'PR0003', 'PR0174', 'PR0080', 'PR0020', 'PR0072',
       'PR0165', 'PR0082', 'PR0113', 'PR0016', 'PR0114', 'PR0193',
       'PR0179', 'PR0167', 'PR0157', 'PR0042', 'PR0136', 'PR0163',
       'PR0135', 'PR0001', 'PR0199', 'PR0144', 'PR0074', 'PR0195',
       'PR0152', 'PR0151', 'PR0147', 'PR0022', 'PR0031'], dtype=object)

In [29]:
sales

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01 00:00:00,HYD-03,CUST007684,SKU00565,4,72.73,19.52,<NA>,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14 00:00:00,HYD-03,CUST004865,SKU01082,6,273.62,173.52,<NA>,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05 00:00:00,BEN-05,CUST006245,SKU00901,2,58.95,4.42,<NA>,Store Pickup,Card,Delivered
4,ORD1000004,2025-03-01 00:00:00,PUN-01,CUST000981,SKU00215,2,91.13,16.68,<NA>,Home Delivery,Cash,Delivered
5,ORD1000005,2025-05-02 00:00:00,AHM-02,CUST005962,SKU01171,2,121.66,19.08,<NA>,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
79995,ORD1079995,2025-04-13 00:00:00,PUN-04,CUST011175,SKU00850,4,85.12,148.80,<NA>,Home Delivery,Card,Delivered
79996,ORD1079996,2025-02-04 00:00:00,PUN-01,CUST002630,SKU01051,3,67.84,97.53,<NA>,Store Pickup,Card,Delivered
79997,ORD1079997,2025-04-21 00:00:00,JAI-01,CUST008801,SKU00005,4,175.81,0.00,<NA>,Express,NaN,Delivered
79998,ORD1079998,2025-04-02 00:00:00,CHE-01,CUST007718,SKU00173,4,44.91,34.32,<NA>,Home Delivery,NetBanking,Delivered
79999,ORD1079999,2025-05-23 00:00:00,MUM-01,CUST003600,SKU00250,3,138.58,90.33,<NA>,Home Delivery,NetBanking,Delivered

In [30]:
sales['Order_Date'] = pd.to_datetime(
    sales['Order_Date'],
    dayfirst=True,
    errors='coerce'
)

In [31]:
sales.dtypes

Order_ID                   object
Order_Date         datetime64[ns]
Store_ID                   object
Customer_ID                object
SKU_ID                     object
Quantity                    int64
Selling_Price             float64
Discount_Amount           float64
Promo_ID                   object
Delivery_Type              object
Payment_Mode               object
Order_Status               object
dtype: object

In [19]:


# 1. Clean Store_ID: Ensure uppercase and correct dash placement (e.g., hyd03 -> HYD-03)
# We use regex to insert a dash if it's missing between letters and numbers
sales['Store_ID'] = sales['Store_ID'].str.upper().str.replace(r'([A-Z]{3})(\d{2})', r'\1-\2', regex=True)

# 2. Clean Customer_ID: Ensure 'CUST' prefix and 7-digit padding (e.g., CUST981 -> CUST000981)
# This extracts the digits and pads them to a total length of 10 characters including 'CUST'
sales['Customer_ID'] = sales['Customer_ID'].str.upper().str.extract(r'(\d+)').iloc[:,0]
sales['Customer_ID'] = 'CUST' + sales['Customer_ID'].str.zfill(6)

# 3. Clean SKU_ID: Ensure 'SKU' prefix and 5-digit padding (e.g., SKU565 -> SKU00565)
# Similar to Customer_ID, we extract the numeric part and re-standardize
sales['SKU_ID'] = sales['SKU_ID'].str.upper().str.extract(r'(\d+)').iloc[:,0]
sales['SKU_ID'] = 'SKU' + sales['SKU_ID'].str.zfill(5)

# List of columns to clean
cols_to_fix = [ 'Customer_ID', 'SKU_ID']

# Loop through and remove hyphens
for col in cols_to_fix:
    sales[col] = sales[col].str.replace('-', '', regex=False)

# Display results to verify
print(sales[cols_to_fix].head())

  Customer_ID    SKU_ID
0  CUST007684  SKU00565
1  CUST004865  SKU01082
2  CUST006245  SKU00901
4  CUST000981  SKU00215
5  CUST005962  SKU01171

In [20]:
sales

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,<NA>,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,<NA>,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,<NA>,Store Pickup,Card,Delivered
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,<NA>,Home Delivery,Cash,Delivered
5,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,<NA>,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
79995,ORD1079995,2025-04-13,PUN-04,CUST011175,SKU00850,4,85.12,148.80,<NA>,Home Delivery,Card,Delivered
79996,ORD1079996,2025-02-04,PUN-01,CUST002630,SKU01051,3,67.84,97.53,<NA>,Store Pickup,Card,Delivered
79997,ORD1079997,2025-04-21,JAI-01,CUST008801,SKU00005,4,175.81,0.00,<NA>,Express,NaN,Delivered
79998,ORD1079998,2025-04-02,CHE-01,CUST007718,SKU00173,4,44.91,34.32,<NA>,Home Delivery,NetBanking,Delivered
79999,ORD1079999,2025-05-23,MUM-01,CUST003600,SKU00250,3,138.58,90.33,<NA>,Home Delivery,NetBanking,Delivered

In [21]:
sales.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\sales_cleaned.xlsx",index = False)

Returns Dataset

In [67]:
returns=pd.read_excel(r'C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Raw\returns_raw.xlsx')
returns

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11 00:00:00,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29 00:00:00,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02 00:00:00,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19 00:00:00,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17 00:00:00,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4695,RET-5375493,ORD-2591995,SKU00447,2025-02-27 00:00:00,Damaged,255.96,Approved
4696,RET-1794775,ORD-2921470,SKU00191,2025-03-24 00:00:00,Late Delivery,148.43,Approved
4697,RET-2924226,ORD-4438000,SKU00195,2025-03-26 00:00:00,Damaged,1183.18,Approved
4698,RET-8454564,ORD-3418454,SKU00447,2025-04-05 00:00:00,Damaged,562.80,Approved
4699,RET-6793261,ORD-8923464,SKU00699,2025-07-08 00:00:00,Wrong Item,70.34,Approved

In [68]:

returns.loc[:, 'Return_Date'] = pd.to_datetime(
    returns['Return_Date'],
    dayfirst=True,
    errors='coerce'
).dt.date

In [69]:
# Fill null values in the Return_Reason column
returns['Return_Reason'] = returns['Return_Reason'].fillna('Unknown')

print(returns.isnull().sum())

Return_ID         0
Order_ID          0
SKU_ID            0
Return_Date      47
Return_Reason     0
Refund_Amount     0
Return_Status     0
dtype: int64

In [70]:
returns = returns.drop_duplicates(subset=['Return_ID'])

In [71]:
# 1. Remove hyphens using .loc
cols_to_fix = ['Return_ID', 'Order_ID']

for col in cols_to_fix:
    returns.loc[:, col] = returns[col].str.replace('-', '', regex=False)

# 2. Final check for SKU_ID using .loc
returns.loc[:, 'SKU_ID'] = returns['SKU_ID'].str.replace('-', '', regex=False)

In [72]:
returns

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4695,RET5375493,ORD2591995,SKU00447,2025-02-27,Damaged,255.96,Approved
4696,RET1794775,ORD2921470,SKU00191,2025-03-24,Late Delivery,148.43,Approved
4697,RET2924226,ORD4438000,SKU00195,2025-03-26,Damaged,1183.18,Approved
4698,RET8454564,ORD3418454,SKU00447,2025-04-05,Damaged,562.80,Approved
4699,RET6793261,ORD8923464,SKU00699,2025-07-08,Wrong Item,70.34,Approved

In [75]:
# Keep ONLY the return records where the Order_ID exists in the sales table
returns = returns[returns['Order_ID'].isin(sales['Order_ID'])]

In [76]:
returns.to_excel(r"C:\Users\hites\OneDrive\Desktop\Retail Chain Profit Leakage & Demand Optimization\Excel\Cleaned\returns_cleaned.xlsx",index = False)